### PR TITLE
feat: custom key

### PR DESCRIPTION
**Pull request by simone-sanfratello**
The idea is to to append data to the caching key in order to allow private content caching, as in the example `custom-key.js`

~~The PR is a draft~~

### CODE REVIEW

**Comment by mcollina** [comment]
I'm wondering if this make sense from a practical perspective. Should we use caching space to cache things for a single user?

**Comment by simone-sanfratello** [comment]
there are private contents that are doesn't change often, for example personal user data, that can be cached to avoid to retrieve them from data source - database or so

**Comment by mcollina** [comment]
I have a feeling this is an antipattern. Let's say we have 2 million users and each one stores 1 KB: here is 1 GB of data.

**Comment by simone-sanfratello** [comment]
if I need to speed up private queries, I think it's ok to use a cache, until the cost of caching worth to avoid computation, like a kind of denormalization

**Comment by mcollina** [comment]
go ahead and finish this off!

**Comment by simone-sanfratello** [comment]
done :)

I don't get what is not working on node 12 (loader?), on 14/16 is running fine

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
