### PR TITLE
Drop Node v14.x, Add Node.js v20.x

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by mcollina** [comment]
@simone-sanfratello @simoneb I'll cut a major afterwards

**Comment by simoneb** [comment]
In some repos we've also been using this https://github.com/pkgjs/action/, which automatically creates the matrix of Node.js versions based on the engines in the package file

**Comment by mcollina** [comment]
That'd be handy!

**Comment by mcollina** [comment]
Are you ok for this change or are you planning some semver-major PRs?

**Comment by simoneb** [comment]
> Are you ok for this change or are you planning some semver-major PRs?

No plans for majors atm

**Pull request merged**
